version: "3.7"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus_data:/prometheus  # 持久化 Prometheus 的數據
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # 配置文件
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana  # 持久化 Grafana 的數據
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # 設定 Grafana 管理員用戶名
      - GF_SECURITY_ADMIN_PASSWORD=admin  # 設定 Grafana 管理員密碼
